####PROD DATABASE CONFIGURATION####
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mealmanage_live_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:YOUR_DB_PASSWORD}

caterer.domain=kitchen
district.domain=district

####Spring boot Service Port####
server.port = 8296

####AWS credential for S3 PROD bucket####
amazon.s3.accesskey=${AWS_ACCESS_KEY:YOUR_AWS_ACCESS_KEY}
amazon.s3.secretkey=${AWS_SECRET_KEY:YOUR_AWS_SECRET_KEY}
amazon.s3.bucket=mealmanage-prod
amazon.s3.endpoint=https://s3.us-east-1.amazonaws.com

#####Prod Details for Data Sync process#####
sqs.queue.name= Prod_MMDataSync_Queue
amazon.s3.sqs.endpoint=https://sqs.us-east-1.amazonaws.com/100655985724/Prod_MMDataSync_Queue
amazon.s3.dataSyncFile.folder=DataSyncOriginalFile/
amazon.s3.dataSyncBackupFile.folder=DataSyncFileBackup/

#####stripe master Account details############
stripe.secret.key=${STRIPE_SECRET_KEY:YOUR_STRIPE_SECRET_KEY}
stripe.client.id=${STRIPE_CLIENT_ID:YOUR_STRIPE_CLIENT_ID}

####Production email API URL for send the notification through email & SMS####
email.notification.url=https://emailapi.mealmanage.com/userRegistration
sms.send.url=https://smsapi.mealmanage.com/sendSMS
email.opt.url=https://emailapi.mealmanage.com/regOTP
reset.pwd.email.url=https://emailapi.mealmanage.com/resetPassword
school.reg.email.url=https://emailapi.mealmanage.com/regSchoolAdmin
menu.pdf.email.url=https://emailapi.mealmanage.com/createMealPdf
mealOrder.update.notification.url=https://emailapi.mealmanage.com/mealorderUpdate
payment.status.notification.url=https://emailapi.mealmanage.com/mealpaymentUpdate
lunch.order.reminder=https://emailapi.mealmanage.com/lunchOrderReminder
reports.email.notification=https://emailapi.mealmanage.com/sendReports
survey.email.notification=https://emailapi.mealmanage.com/mealEligibilityCheck
publish.menu.email.notif=https://emailapi.mealmanage.com/mealPublishNotification
menu.pdf.email.cancel.url=https://emailapi.mealmanage.com/orderItemsCancellation
support.email.notification=https://emailapi.mealmanage.com/support
datasync.email.notification=https://emailapi.mealmanage.com/dataSync
stripe.setup.email.notification=https://devemailapi.mealmanage.com/stripeSetup
stripe.setup.status.notification=https://devemailapi.mealmanage.com/stripeSetupStatus
payment.receipt.notification=https://devemailapi.mealmanage.com/paymentReceipt
household.application.apprvDecline=https://emailapi.mealmanage.com/householdAppAprvDecline
household.application.apprvDeclineV2=https://emailapi.mealmanage.com/householdAppAprvDeclineV2
demo.requestEmail.url=https://emailapi.mealmanage.com/demoRequest
household.application.emailUrl=https://emailapi.mealmanage.com/householdApplication
support.self.notification=https://emailapi.mealmanage.com/supportAutomatedEmail
request.self.notification=https://emailapi.mealmanage.com/requestAutomatedEmail
event.publish.notification=https://emailapi.mealmanage.com/eventEmail
caterer.report.notification=https://emailapi.mealmanage.com/catererReport

district.partner.token=https://partnerapi.mealmanage.com/token?districtId=<<distId>>&partnerId=<<pId>>

####Mealmanage application subdomain for Super Admin user or Parent user####
spring.mealmanage.subdomain=app

####Spring Boot Admin Server setup for monitor the PROD API####
info.app.name=PROD Mealmanage App
info.app.description=This is a PROD Mealmanage application!
info.app.version=1.0.0
spring.application.name=PROD Mealmanage Application
#spring.boot.admin.url=https://admin.mealmanage.com/
spring.boot.admin.username=SpringBootAdmin
spring.boot.admin.password=${ADMIN_PASSWORD:YOUR_ADMIN_PASSWORD}
management.security.enabled=false
#logging.file=target/${spring.application.name}.log

######SFTP CONFIG#######
sftp.host=transfer.mealmanage.com
sftp.user=${SFTP_USER:YOUR_SFTP_USER}
sftp.password=${SFTP_PASSWORD:YOUR_SFTP_PASSWORD}
sftp.remote.directory.download=/home/prod/
sftp.remote.directory.success=/home/prod/success/
sftp.remote.directory.failure=/home/prod/failure/
