####DEV DATABASE CONFIGURATION DETAILS####
#spring.datasource.url=jdbc:mysql://mealmanage-dev-db-instance.clzdb7ax6zr0.us-east-1.rds.amazonaws.com:3306/MM_dev_withTier
spring.datasource.url=jdbc:mysql://mealmanage-dev-db-aurora-instance.clzdb7ax6zr0.us-east-1.rds.amazonaws.com:3306/MM_QA_DB
spring.datasource.username=tmroot
spring.datasource.password=tempe1q2w9o0p
#spring.datasource.url=jdbc:mysql://localhost:3306/MM_dev_withTier
#spring.datasource.username=root
#spring.datasource.password=root

caterer.domain=qakitchen
district.domain=qavdistrict

####Spring boot Service Port####
server.port = 8296

####AWS credential for S3 DEV bucket####
amazon.s3.accesskey=${AWS_ACCESS_KEY:YOUR_AWS_ACCESS_KEY}
amazon.s3.secretkey=${AWS_SECRET_KEY:YOUR_AWS_SECRET_KEY}
amazon.s3.bucket=mealmanageordered
amazon.s3.endpoint=https://s3.us-east-1.amazonaws.com

#####Dev Details for Data Sync process#####
sqs.queue.name= Dev_MMDataSync_Queue
amazon.s3.sqs.endpoint=https://sqs.us-east-1.amazonaws.com/100655985724/Dev_MMDataSync_Queue
amazon.s3.dataSyncFile.folder=DataSyncOriginalFile/
amazon.s3.dataSyncBackupFile.folder=DataSyncFileBackup/

#####stripe master Account details############
stripe.secret.key=${STRIPE_SECRET_KEY:YOUR_STRIPE_SECRET_KEY}
stripe.client.id=${STRIPE_CLIENT_ID:YOUR_STRIPE_CLIENT_ID}

####DEV Email API URL for send the notification through email & SMS####
email.notification.url=https://devemailapi.mealmanage.com/userRegistration
sms.send.url=https://smsapi.mealmanage.com/sendSMS
email.opt.url=https://devemailapi.mealmanage.com/regOTP
reset.pwd.email.url=https://devemailapi.mealmanage.com/resetPassword
school.reg.email.url=https://devemailapi.mealmanage.com/regSchoolAdmin
menu.pdf.email.url=https://devemailapi.mealmanage.com/createMealPdf
mealOrder.update.notification.url=https://devemailapi.mealmanage.com/mealorderUpdate
payment.status.notification.url=https://devemailapi.mealmanage.com/mealpaymentUpdate
lunch.order.reminder=https://devemailapi.mealmanage.com/lunchOrderReminder
reports.email.notification=https://devemailapi.mealmanage.com/sendReports
survey.email.notification=https://devemailapi.mealmanage.com/mealEligibilityCheck
publish.menu.email.notif=https://devemailapi.mealmanage.com/mealPublishNotification
menu.pdf.email.cancel.url=https://devemailapi.mealmanage.com/orderItemsCancellation
support.email.notification=https://devemailapi.mealmanage.com/support
datasync.email.notification=https://devemailapi.mealmanage.com/dataSync
stripe.setup.email.notification=https://devemailapi.mealmanage.com/stripeSetup
stripe.setup.status.notification=https://devemailapi.mealmanage.com/stripeSetupStatus
payment.receipt.notification=https://devemailapi.mealmanage.com/paymentReceipt
household.application.apprvDecline=https://devemailapi.mealmanage.com/householdAppAprvDecline
household.application.apprvDeclineV2=https://devemailapi.mealmanage.com/householdAppAprvDeclineV2
demo.requestEmail.url=https://devemailapi.mealmanage.com/demoRequest
household.application.emailUrl=https://devemailapi.mealmanage.com/householdApplication
support.self.notification=https://devemailapi.mealmanage.com/supportAutomatedEmail
request.self.notification=https://devemailapi.mealmanage.com/requestAutomatedEmail
event.publish.notification=https://devemailapi.mealmanage.com/eventEmail
caterer.report.notification=https://devemailapi.mealmanage.com/catererReport

district.partner.token=https://devpartnerapi.mealmanage.com/token?districtId=<<distId>>&partnerId=<<pId>>

####Mealmanage application Dev subdomain for Super Admin user or Parent user####
spring.mealmanage.subdomain=qaapp

####Spring Boot Admin Server setup for monitor the DEV API####
info.app.name=QA Mealmanage App
info.app.description=This is a QA Mealmanage application!
info.app.version=1.0.0
spring.application.name=QA Mealmanage Application
#spring.boot.admin.url=https://admin.mealmanage.com/
spring.boot.admin.username=SpringBootAdmin
spring.boot.admin.password=Techm@1234$
management.security.enabled=false
#logging.file=target/${spring.application.name}.log

sftp.host=transfer.mealmanage.com
sftp.user=mmtestuser
sftp.password=Meal123$
sftp.remote.directory.download=/home/qa/
sftp.remote.directory.success=/home/qa/success/
sftp.remote.directory.failure=/home/qa/failure/
