####This below line command should be update when want to create/update any entity else it should be always as none.####
spring.jpa.hibernate.ddl-auto=update

####Hibernate entity naming strategy####
spring.jpa.properties.hibernate.physical_naming_strategy=com.mealManage.RealNamingStrategyImpl

####These below two line should be uncomment only when want to execute the specified sql scripts else it should be commented always####
#spring.datasource.data=classpath:/sql/schema_v5.sql 
#spring.datasource.separator=^;

####HIKARI Database connection pool settings######
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=MealManageAPIHikariCP
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

####Spring data rest API base path####
spring.data.rest.base-path=/mealManage

##URL for generate oauth2 access & refresh token token
auth.token.url=http://localhost:<<port>>/oauth/token

mm.support.email=support@mealmanage.com
mm.contact.email=contact@mealmanage.com

####Folder name for upload the files on S3 bucket####
amazon.s3.schoolLogo.folder=MealSchoolLogo/
amazon.s3.mealsExcelImport.folder=MealsImportExcel/
amazon.s3.mealMenuPdf.folder=SchoolMealMenu/
amazon.s3.orderedMenuPdf.folder=OrderedMenu/
amazon.s3.schoolReport.folder=SchoolReports/
amazon.s3.catererReport.folder=CatererReports/
amazon.s3.studentBkp.folder=studentBackupFiles/
amazon.s3.schoolPdf.folder=schoolPdfFiles/
amazon.s3.benefitsNotice.folder=benefitsNoticeLetters/
amazon.s3.menuItemImage.folder=MenuItemImage/
amazon.s3.stdCertImport.folder=CertificationDateImportExcel/

####Spring JPA & other properties configuration####
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = false
logging.level.org.hibernate.SQL=error
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=error
security.oauth2.resource.filter-order = 3

####Mealmanage application base domain name####
spring.mail.domainName=mealmanage.com/

##Federal Eligibility Income Chart for School Year 2019-2020
federal.poverty_limit=12880
federal.poverty.increment=4540

######Stripe Acccount URLs######
stripe.base.url=https://connect.stripe.com/
stripe.account.setup.url=oauth/authorize?response_type=code&client_id=<<clientId>>&scope=read_write

####Quartz Scheduler time to execute the Job (e.g. 06:00 AM everyday)####
cron.exp=0 0 13 ? * *

####increase  spring data rest api result page size
spring.data.rest.default-page-size=100000

####Email & SMS template message body#####
sms.otp.messages=Your security code is <<otp>>
sms.otp.message.type=PERSONAL
email.payment.reminder.subject=Payment due reminder from <<schoolName>> Mealmanage portal
email.payment.reminder.message=We have not received the payment for your <<month>> lunch order. Please arrange the payment as soon as possible. Thanks for your cooperation.
email.lunch.change.reminder.subject=Lunch meal item changed from <<schoolName>> Mealmanage portal
email.lunch.change.remider.message=Your ordered meal item <<oldMealItem>> got replaced with new item <<newItem>> due to unavailable on <<mealDate>>.
student.export.headers=firstName,lastName,gradeName,studentId,teacherName,userName,isReducePriceEligible,isFreeMealEligible,parentAltEmail,mobileNo,numberStreetApt,cityStateZip,isBeforeCare,hasMilkCard,isEnrollBCAndACPkt,pin,accBalance,allergies,schoolStudentId,isRegister,isActive,userId

###Notice benefits letter text
notice.benefits.principalTxt=If you do not agree with the decision you may discuss it with the school official.  You also have the right to a fair hearing.  This can be done by contacting the following official:
notice.benefits.FoodManagerTxt=You are able to re-apply for free and reduced-price benefits at any time during the school year by completing another application.
notice.benefits.footer1=In accordance with Federal civil rights law and U.S. Department of Agriculture (USDA) civil rights regulations and policies, the USDA, its Agencies, offices, and employees, and institutions participating in or administering USDA programs are prohibited from discriminating based on race, color, national origin, sex, disability, age, or reprisal or retaliation for prior civil rights activity in any program or activity conducted or funded by USDA.
notice.benefits.footer2=Persons with disabilities who require alternative means of communication for program information (e.g., Braille, large print, audiotape, American Sign Language, etc.) should contact the Agency (State or local) where they applied for benefits. Individuals who are deaf, hard of hearing or have speech disabilities may contact USDA through the Federal Relay Service at (800) 877-8339. Additionally, program information may be made available in languages other than English.
notice.benefits.footer3=To file a program complaint of discrimination, complete the USDA Program Discrimination Complaint Form, AD-3027, found online at http://www.ascr.usda.gov/complaint_filing_cust.html, and at any USDA office, or write a letter addressed to USDA and provide in the letter all of the information requested in the form. To request a copy of the complaint form, call (866) 632-9992. Submit your completed form or letter to USDA by: (1) mail: U.S. Department of Agriculture, Office of the Assistant Secretary for Civil Rights, 1400 Independence Avenue, SW, Washington, D.C. 20250-9410; (2) fax: (202) 690-7442; or (3) email: program.intake@usda.gov. This institution is an equal opportunity provider.

#logging.level.org.springframework=off
#logging.level.root=error